# Site wide configuration

title: UVW.no
description: "Litt av alt"
logo: 120x120.gif
teaser: 400x250.gif
locale: nb_NO
url: //jekyll.hinderaker.solutions

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Glenn M. Hinderaker
  web: http://twitter.com/gmhinderaker
  email: glenn@hinderaker.com
  twitter: gmhinderaker
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    ad-client: ca-pub-8017141228726570
    ad-slot: 1356314640
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
